### PR TITLE
Don't include a `command` hook

### PR DESCRIPTION
**Pull request by staticfloat**
This was here because if you don't provide a `command` mapping in your
step, and no plugin provides a `command` hook, buildkite complains.

However, this can cause the user's command to be run multiple times, so
it's better to just require people to manually provide a command, I
think.

### CODE REVIEW

**Comment by staticfloat** [comment]
@DilumAluthge this is a necessary change, but it's breaking, so I'm thinking we should make sure all current usages of `cryptic` are using `v1` as the tag to download, and then release this as `v2`.

**Comment by DilumAluthge** [comment]
Agreed. For the JuliaLang/julia repo, we can just grep the `.buildkite` folder for the word `cryptic`.

How many other repos are using the cryptic plugin?

**Comment by DilumAluthge** [comment]
> For the JuliaLang/julia repo, we can just grep the `.buildkite` folder for the word `cryptic`.

Actually, for JuliaLang/julia, it might be easier to wait until we have finished moving the `.buildkite ` folder to JuliaCI/julia-builkite, and then fix the invocations of `cryptic` in the latter repository.

**Comment by DilumAluthge** [comment]
> it's better to just require people to manually provide a command, I
> think.

Yeah I think it's better to have them explicit provide a command.

**Pull request merged**
